# Generated by Django 2.1.4 on 2019-01-04 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uniauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionaccount',
            name='status',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('pending', 'Pending'), ('verified', 'Verified')], default='inactive', max_length=10),
        ),
        migrations.AddField(
            model_name='linkedemail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='institution',
            name='slug',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
