# Generated by Django 2.1.4 on 2019-01-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniauth', '0002_auto_20190104_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionaccount',
            name='status',
        ),
        migrations.RemoveField(
            model_name='linkedemail',
            name='status',
        ),
        migrations.AddField(
            model_name='linkedemail',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
